DATA = {
    0: {
        'json': [
            {'0': ''},
            [1.0, 2.0],
            1.0,
            2,
            "asdf",
        ],
        'reference': {
            (0,): {'start': 2, 'end': 13, 'type': 'table'},
            (0, '0'): {'start': 10, 'end': 10, 'type': 'string'},
            (1,): {'start': 15, 'end': 27, 'type': 'array'},
            (1, 0): {'start': 17, 'end': 20, 'type': 'float'},
            (1, 1): {'start': 22, 'end': 25, 'type': 'float'},
            (2,): {'start': 29, 'end': 32, 'type': 'float'},
            (3,): {'start': 34, 'end': 35, 'type': 'integer'},
            (4,): {'start': 38, 'end': 42, 'type': 'string'},
        },
        'reference_crlf': {
            (0,): {'start': 3, 'end': 16, 'type': 'table'},
            (0, '0'): {'start': 12, 'end': 12, 'type': 'string'},
            (1,): {'start': 19, 'end': 34, 'type': 'array'},
            (1, 0): {'start': 22, 'end': 25, 'type': 'float'},
            (1, 1): {'start': 28, 'end': 31, 'type': 'float'},
            (2,): {'start': 37, 'end': 40, 'type': 'float'},
            (3,): {'start': 43, 'end': 44, 'type': 'integer'},
            (4,): {'start': 48, 'end': 52, 'type': 'string'},
        },
        'values': {
            (0,): {'0': ''},
            (0, '0'): '',
            (1,): [1.0, 2.0],
            (1, 0): 1.0,
            (1, 1): 2.0,
            (2,): 1.0,
            (3,): 2,
            (4,): "asdf",
        }
    },
    1: {
        'json': {
            '0': '',
            'a': 1,
            'b': [1.0, 2.0],
            'c': {'d': [1.2, -2.0], 'efg': [-4]},
            'hij': 'klmn',
        },
        'reference': {
            ('0',): {'start': 8, 'end': 8, 'type': 'string'},
            ('a',): {'start': 16, 'end': 17, 'type': 'integer'},
            ('b',): {'start': 24, 'end': 36, 'type': 'array'},
            ('b', 0): {'start': 26, 'end': 29, 'type': 'float'},
            ('b', 1): {'start': 31, 'end': 34, 'type': 'float'},
            ('c',): {'start': 43, 'end': 80, 'type': 'table'},
            ('c', 'd'): {'start': 50, 'end': 63, 'type': 'array'},
            ('c', 'd', 0): {'start': 52, 'end': 55, 'type': 'float'},
            ('c', 'd', 1): {'start': 57, 'end': 61, 'type': 'float'},
            ('c', 'efg'): {'start': 72, 'end': 78, 'type': 'array'},
            ('c', 'efg', 0): {'start': 74, 'end': 76, 'type': 'integer'},
            ('hij',): {'start': 90, 'end': 94, 'type': 'string'},
        },
        'reference_crlf': {
            ('0',): {'start': 9, 'end': 9, 'type': 'string'},
            ('a',): {'start': 18, 'end': 19, 'type': 'integer'},
            ('b',): {'start': 27, 'end': 42, 'type': 'array'},
            ('b', 0): {'start': 30, 'end': 33, 'type': 'float'},
            ('b', 1): {'start': 36, 'end': 39, 'type': 'float'},
            ('c',): {'start': 50, 'end': 95, 'type': 'table'},
            ('c', 'd'): {'start': 58, 'end': 74, 'type': 'array'},
            ('c', 'd', 0): {'start': 61, 'end': 64, 'type': 'float'},
            ('c', 'd', 1): {'start': 67, 'end': 71, 'type': 'float'},
            ('c', 'efg'): {'start': 84, 'end': 92, 'type': 'array'},
            ('c', 'efg', 0): {'start': 87, 'end': 89, 'type': 'integer'},
            ('hij',): {'start': 106, 'end': 110, 'type': 'string'},
        },
        'values': {
            ('0',): '',
            ('a',): 1,
            ('b',): [1.0, 2.0],
            ('b', 0): 1.0,
            ('b', 1): 2.0,
            ('c',): {'d': [1.2, -2.0], 'efg': [-4]},
            ('c', 'd'): [1.2, -2.0],
            ('c', 'd', 0): 1.2,
            ('c', 'd', 1): -2.0,
            ('c', 'efg'): [-4],
            ('c', 'efg', 0): -4,
            ('hij',): 'klmn',
        }
    }
}
